/**
 * QR-Based Restaurant Management System APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import { MenuResponse, menuResponseSchema } from '../models/menuResponse.js';
import { BaseController } from './baseController.js';

export class MenuController extends BaseController {
  /**
   * @return Response from the API call
   */
  async getAllMenuItems(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<MenuResponse>> {
    const req = this.createRequest('GET', '/menu');
    return req.callAsJson(menuResponseSchema, requestOptions);
  }
}
