/**
 * QR-Based Restaurant Management System APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import { MenuItem, menuItemSchema } from '../models/menuItem.js';
import { array } from '../schema.js';
import { BaseController } from './baseController.js';

export class MenuController extends BaseController {
  /**
   * @return Response from the API call
   */
  async getAllMenuItems(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<MenuItem[]>> {
    const req = this.createRequest('GET', '/menu');

    // Parse as raw JSON first (no schema check yet)
    const response = await req.callAsJson((json) => json, requestOptions);

    // Fix shape: return only the array
    return {
      ...response,
      result: response.result.data ?? []
    };
  }

}
