/**
 * QR-Based Restaurant Management System APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import { Order, orderSchema } from '../models/order.js';
import { OrderInput, orderInputSchema } from '../models/orderInput.js';
import { array } from '../schema.js';
import { BaseController } from './baseController.js';

export class OrderController extends BaseController {
  /**
   * @param body
   * @return Response from the API call
   */
  async placeANewOrder(
    body: OrderInput,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Order>> {
    const req = this.createRequest('POST', '/order/place-order');
    const mapped = req.prepareArgs({ body: [body, orderInputSchema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    return req.callAsJson(orderSchema, requestOptions);
  }

  /**
   * @return Response from the API call
   */
  async getOrderHistory(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Order[]>> {
    const req = this.createRequest('GET', '/order/history');
    return req.callAsJson(array(orderSchema), requestOptions);
  }
}
