/**
 * QR-Based Restaurant Management System APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  OrderHistoryResponse,
  orderHistoryResponseSchema,
} from '../models/orderHistoryResponse.js';
import { OrderInput, orderInputSchema } from '../models/orderInput.js';
import { OrderResponse, orderResponseSchema } from '../models/orderResponse.js';
import { BaseController } from './baseController.js';

export class OrderController extends BaseController {
  /**
   * @param body
   * @return Response from the API call
   */
  async placeANewOrder(
    body: OrderInput,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<OrderResponse>> {
    const req = this.createRequest('POST', '/order/place-order');
    const mapped = req.prepareArgs({ body: [body, orderInputSchema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    return req.callAsJson(orderResponseSchema, requestOptions);
  }

  /**
   * @return Response from the API call
   */
  async getOrderHistory(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<OrderHistoryResponse>> {
    const req = this.createRequest('GET', '/order/history');
    return req.callAsJson(orderHistoryResponseSchema, requestOptions);
  }
}
