/**
 * QR-Based Restaurant Management System APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface CustomerDetails1 {
  contact?: string;
  address?: string;
  additionalProperties?: Record<string, unknown>;
}

export const customerDetails1Schema: Schema<CustomerDetails1> = typedExpandoObject(
  {
    contact: ['contact', optional(string())],
    address: ['address', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
