/**
 * QR-Based Restaurant Management System APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface CustomerDetails {
  contact: string;
  address: string;
  additionalProperties?: Record<string, unknown>;
}

export const customerDetailsSchema: Schema<CustomerDetails> = typedExpandoObject(
  { contact: ['contact', string()], address: ['address', string()] },
  'additionalProperties',
  optional(unknown())
);
