/**
 * QR-Based Restaurant Management System APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Item {
  menuItemId?: string;
  quantity?: number;
  additionalProperties?: Record<string, unknown>;
}

export const itemSchema: Schema<Item> = typedExpandoObject(
  {
    menuItemId: ['menuItemId', optional(string())],
    quantity: ['quantity', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
