/**
 * QR-Based Restaurant Management System APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Item1 {
  menuItem?: string;
  quantity?: number;
  additionalProperties?: Record<string, unknown>;
}

export const item1Schema: Schema<Item1> = typedExpandoObject(
  {
    menuItem: ['menuItem', optional(string())],
    quantity: ['quantity', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
