/**
 * QR-Based Restaurant Management System APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface MenuItem {
  id?: string;
  name?: string;
  description?: string;
  price?: number;
  category?: string;
  image?: string;
  isAvailable?: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const menuItemSchema: Schema<MenuItem> = typedExpandoObject(
  {
    id: ['_id', optional(string())],
    name: ['name', optional(string())],
    description: ['description', optional(string())],
    price: ['price', optional(number())],
    category: ['category', optional(string())],
    image: ['image', optional(string())],
    isAvailable: ['isAvailable', optional(boolean())],
  },
  'additionalProperties',
  optional(unknown())
);
