/**
 * QR-Based Restaurant Management System APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { MenuItem, menuItemSchema } from './menuItem.js';

export interface MenuResponse {
  success?: boolean;
  count?: number;
  data?: MenuItem[];
  additionalProperties?: Record<string, unknown>;
}

export const menuResponseSchema: Schema<MenuResponse> = typedExpandoObject(
  {
    success: ['success', optional(boolean())],
    count: ['count', optional(number())],
    data: ['data', optional(array(lazy(() => menuItemSchema)))],
  },
  'additionalProperties',
  optional(unknown())
);
