/**
 * QR-Based Restaurant Management System APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Order, orderSchema } from './order.js';

export interface OrderHistoryResponse {
  success?: boolean;
  count?: number;
  data?: Order[];
  additionalProperties?: Record<string, unknown>;
}

export const orderHistoryResponseSchema: Schema<OrderHistoryResponse> = typedExpandoObject(
  {
    success: ['success', optional(boolean())],
    count: ['count', optional(number())],
    data: ['data', optional(array(lazy(() => orderSchema)))],
  },
  'additionalProperties',
  optional(unknown())
);
