/**
 * QR-Based Restaurant Management System APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for OrderType
 */
export enum OrderType {
  Dinein = 'dine-in',
  Takeaway = 'takeaway',
  Delivery = 'delivery',
}

/**
 * Schema for OrderType
 */
export const orderTypeSchema: Schema<OrderType> = stringEnum(OrderType);
