/**
 * QR-Based Restaurant Management System APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Item, itemSchema } from './item.js';

export interface OrderInput {
  items: Item[];
  tableNumber: number;
  additionalProperties?: Record<string, unknown>;
}

export const orderInputSchema: Schema<OrderInput> = typedExpandoObject(
  {
    items: ['items', array(lazy(() => itemSchema))],
    tableNumber: ['tableNumber', number()],
  },
  'additionalProperties',
  optional(unknown())
);
