/**
 * QR-Based Restaurant Management System APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Order, orderSchema } from './order.js';

export interface OrderResponse {
  success?: boolean;
  data?: Order;
  additionalProperties?: Record<string, unknown>;
}

export const orderResponseSchema: Schema<OrderResponse> = typedExpandoObject(
  {
    success: ['success', optional(boolean())],
    data: ['data', optional(lazy(() => orderSchema))],
  },
  'additionalProperties',
  optional(unknown())
);
