/**
 * QR-Based Restaurant Management System APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Item, itemSchema } from './item.js';

export interface Order {
  id?: string;
  items?: Item[];
  tableNumber?: number;
  status?: string;
  createdAt?: string;
  additionalProperties?: Record<string, unknown>;
}

export const orderSchema: Schema<Order> = typedExpandoObject(
  {
    id: ['_id', optional(string())],
    items: ['items', optional(array(lazy(() => itemSchema)))],
    tableNumber: ['tableNumber', optional(number())],
    status: ['status', optional(string())],
    createdAt: ['createdAt', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
