/**
 * QR-Based Restaurant Management System APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  CustomerDetails1,
  customerDetails1Schema,
} from './customerDetails1.js';
import { Item1, item1Schema } from './item1.js';

export interface Order {
  id?: string;
  items?: Item1[];
  tableNumber?: number;
  totalAmount?: number;
  orderType?: string;
  customerDetails?: CustomerDetails1;
  status?: string;
  createdAt?: string;
  additionalProperties?: Record<string, unknown>;
}

export const orderSchema: Schema<Order> = typedExpandoObject(
  {
    id: ['_id', optional(string())],
    items: ['items', optional(array(lazy(() => item1Schema)))],
    tableNumber: ['tableNumber', optional(number())],
    totalAmount: ['totalAmount', optional(number())],
    orderType: ['orderType', optional(string())],
    customerDetails: [
      'customerDetails',
      optional(lazy(() => customerDetails1Schema)),
    ],
    status: ['status', optional(string())],
    createdAt: ['createdAt', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
